sudo: required

language: c#

install:
  - git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
  - git fetch --no-tags
  - git checkout $TRAVIS_BRANCH
  - sh prepare.sh
  - sh init.sh

script:
  - git remote set-url origin https://$GHTOKEN@github.com/CompulsiveCoder/BridgeArduinoSerialToMqttSplitCsv.git
  - sh test-and-graduate.sh
  - sh nuget-set-api-key.sh $NUGETTOKEN && sh nuget-pack-and-push.sh
  - sh push-version.sh
